# Generated by Django 4.1.5 on 2023-01-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
